<?php
$GLOBALS['admin_cat'] = array(
	'0' => array(
		'id' => '1',
		'pid' => '0',
		'name' => '设置',
		'url' => '###',
		'mark' => '0',
		'comment' => '网站管理',
		'sub' => array(
			'0' => array(
				'id' => '7',
				'pid' => '1',
				'name' => '参数设定',
				'url' => 'web_setting.php',
				'mark' => '0',
				'comment' => '参数设定',
			),
			'1' => array(
				'id' => '8',
				'pid' => '1',
				'name' => '子站管理',
				'url' => 'web_subweb.php',
				'mark' => '0',
				'comment' => '子站管理',
			),
			'2' => array(
				'id' => '9',
				'pid' => '1',
				'name' => '缓存管理',
				'url' => 'web_cache.php',
				'mark' => '0',
				'comment' => '缓存管理',
			),
		),
	),
	'1' => array(
		'id' => '2',
		'pid' => '0',
		'name' => '用户',
		'url' => '###',
		'mark' => '0',
		'comment' => '用户管理',
		'sub' => array(
			'0' => array(
				'id' => '10',
				'pid' => '2',
				'name' => '用户群组',
				'url' => 'user_group.php',
				'mark' => '0',
				'comment' => '组群维护',
			),
			'1' => array(
				'id' => '11',
				'pid' => '2',
				'name' => '用户管理',
				'url' => 'user_detail.php',
				'mark' => '0',
				'comment' => '用户管理',
			),
			'2' => array(
				'id' => '12',
				'pid' => '2',
				'name' => '在线用户',
				'url' => 'user_online.php',
				'mark' => '0',
				'comment' => '在线用户',
			),
		),
	),
	'2' => array(
		'id' => '3',
		'pid' => '0',
		'name' => '功能',
		'url' => '###',
		'mark' => '0',
		'comment' => '网站功能',
		'sub' => array(
			'0' => array(
				'id' => '13',
				'pid' => '3',
				'name' => '文章标签',
				'url' => 'func_tag.php',
				'mark' => '0',
				'comment' => '文章标签管理',
			),
			'1' => array(
				'id' => '14',
				'pid' => '3',
				'name' => '附件管理',
				'url' => 'func_attach.php',
				'mark' => '0',
				'comment' => '附件管理',
			),
			'2' => array(
				'id' => '15',
				'pid' => '3',
				'name' => '友情链接',
				'url' => 'func_link.php',
				'mark' => '0',
				'comment' => '友情链接管理',
			),
			'3' => array(
				'id' => '16',
				'pid' => '3',
				'name' => '数据备份',
				'url' => 'func_backup.php',
				'mark' => '0',
				'comment' => '数据备份',
			),
		),
	),
	'3' => array(
		'id' => '4',
		'pid' => '0',
		'name' => '内容',
		'url' => '###',
		'mark' => '0',
		'comment' => '内容管理',
		'sub' => array(
			'0' => array(
				'id' => '17',
				'pid' => '4',
				'name' => '文章分类',
				'url' => 'art_catalog.php',
				'mark' => '0',
				'comment' => '文章分类管理',
			),
			'1' => array(
				'id' => '18',
				'pid' => '4',
				'name' => '文章内容',
				'url' => 'art_content.php',
				'mark' => '0',
				'comment' => '文章内容管理',
			),
			'2' => array(
				'id' => '19',
				'pid' => '4',
				'name' => '内容展示',
				'url' => 'art_info.php',
				'mark' => '0',
				'comment' => '展示内容管理',
			),
		),
	),
	'4' => array(
		'id' => '5',
		'pid' => '0',
		'name' => '信息',
		'url' => '###',
		'mark' => '0',
		'comment' => '站点信息',
		'sub' => array(
			'0' => array(
				'id' => '20',
				'pid' => '5',
				'name' => '更新日志',
				'url' => 'info_log.php',
				'mark' => '0',
				'comment' => '更新日志',
			),
			'1' => array(
				'id' => '21',
				'pid' => '5',
				'name' => '错误察看',
				'url' => 'info_err.php',
				'mark' => '0',
				'comment' => '错误察看',
			),
			'2' => array(
				'id' => '22',
				'pid' => '5',
				'name' => '访问统计',
				'url' => 'info_count.php',
				'mark' => '0',
				'comment' => '访问统计',
			),
		),
	),
	'5' => array(
		'id' => '6',
		'pid' => '0',
		'name' => '扩展',
		'url' => '###',
		'mark' => '0',
		'comment' => '扩展功能',
		'sub' => array(
			'0' => array(
				'id' => '23',
				'pid' => '6',
				'name' => '插件管理',
				'url' => 'web_plugin.php',
				'mark' => '0',
				'comment' => '插件管理',
			),
		),
	),
);
?>